/**
* Determines the level of logging that the function will output. This enables
* us to reduce the amount of "noise" generated by a battle-tested function,
* whilst enabling us to output additional logging on a new version.
*
* Setting `process.env.LOG_LEVEL` will overwrite the default value of `"info"`
* for this variable.
*
* @type {String}
*/
export const LOG_LEVEL = (process.env.LOG_LEVEL || 'info');

/**
 * The AWS Region that this Lambda function is currently executing in.
 *
 * _Note: This is normally populated by the Lambda execution environment._
 *
 * @type {String}
 */
export const AWS_REGION = process.env.AWS_REGION;


/**
 * The secret API Key used to communicate with the Flood.IO account
 *
 * @type {String}
 */
export const FLOOD_API_KEY = process.env.FLOOD_API_KEY;

/**
 * The URL used to communicate with the Flood.IO API
 *
 * @type {String}
 */
export const FLOOD_API_URI = 'https://api.flood.io/';

/**
 * The path used for sending requests to action Floods
 *
 * @type {String}
 */
export const FLOODS_PATH = 'floods';

/**
 * The path used for sending requests to action Grids
 *
 * @type {String}
 */
export const GRIDS_PATH = 'grids';
